### ISSUE TITLE
Plugin doesn't do anything when writing on openSUSE, but on MacOS it does

### ISSUE THREAD

**Issue by thomasmerz** [itspriddle/vim-shellcheck#11]
I found your fancy ❤️  vim-plugin and use it on **MacOS** and on **openSUSE** (both are my main workstation(s) and servers):

On MacOS it behaves like this:
- 🟩 `shellcheck` on write (`:w`)
   <img width="503" alt="grafik" src="https://user-images.githubusercontent.com/18568381/155143358-170ffb52-bad8-4b19-bc1e-5979649721c8.png">
- 🛑 `shellcheck` on demand (`:Shellcheck!`)
   <img width="501" alt="grafik" src="https://user-images.githubusercontent.com/18568381/155143116-e810784f-ebad-4946-b558-de8e970de7d4.png">

And on openSUSE it only works on demand:
- 🛑  `shellcheck` on write (`:w`)
   (nothing happens at all!?)
- 🟩  `shellcheck` on demand (`:Shellcheck!`)
   <img width="507" alt="grafik" src="https://user-images.githubusercontent.com/18568381/155143275-11df94c0-8a89-49fd-b811-dc2c685aff48.png">

My vim on MacOS:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 24 2021 06:02:32)
macOS version - x86_64
Included patches: 1-3455
Compiled by Homebrew
```
My vim on OpenSUSE:
```
VIM - Vi IMproved 8.0 (2016 Sep 12)
Included patches: 1-1568
Compiled by 'http://www.opensuse.org/'
```
I tried it also with a more current vim on openSUSE (8.2.4375-lp153.721.1), but this didn't make it better in any way…

`shellcheck` on write would be what I prefer. Can you @itspriddle please help what's wrong here? 🤷🏻‍♂️  Thanks a lot!

**Comment by itspriddle** [comment]
Hey @thomasmerz

Are you using any other listing plugins, such as syntastic? This plugin doesn't do anything on `:w` on its own (although you could add it with an `autocmd BufWrite *.sh :ShellCheck!`)

The other thing that stands out is the error from your macOS screenshot using `:ShellCheck!`. Behind the scenes, this plugin creates a temp file [here](https://github.com/itspriddle/vim-shellcheck/blob/4346419ac57ef341a15aa39c827c0848f17c6faf/after/ftplugin/sh.vim#L43), which has the contents of the current buffer (or highlighted text) written to it. This temp file is the one that actually has `spellcheck -f gcc ...` performed on it. The point this plugin is trying to run spellcheck the file is missing. I can't duplicate that on Vim 8.2p4400 from Homebrew on my M1 Macs running macOS 12.2.1 .

It feels like vim-spellcheck is indeed working as designed on your OpenSUSE box, but the temp file issue on macOS is definitely a weird issue I haven't seen myself. 

Are you doing anything out of the ordinary with temp files/dirs on your Mac?

**Comment by thomasmerz** [comment]
Regarding the **tempfile**:
I've set `set directory=~/temp,.` on both MacOS and openSUSE. But also with `set directory=.` or `set directory=` nothing changes with `:ShellCheck!` on 🛑 MacOS or on 🟩 openSUSE.
On MacOS there's `TMPDIR=/var/folders/89/t8gb_dhj0bl_fmcj76pxy4g80000gp/T/` set in my bash:
```
$ ll -d $TMPDIR
drwx------ Thomas.Merz staff 6.0 KB now  /var/folders/89/t8gb_dhj0bl_fmcj76pxy4g80000gp/T/
```
Nothing like this on my openSUSE…

That's really weird:
"/var/folders/89/t8gb_dhj0bl_fmcj76pxy4g80000gp/T/vsvCjOn/3-abc.sh: /var/folders/89/t8gb_dhj0bl_fmcj76pxy4g80000gp/T/vsvCjOn/3-abc.sh: openBinaryFile: does not exist (No such file or directory)" 🤥 
<img width="1536" alt="grafik" src="https://user-images.githubusercontent.com/18568381/155222243-16b7dc15-e86a-4686-9867-f0cf89daadec.png">

**Comment by thomasmerz** [comment]
Here are my **vim-plugins** on:
* MacOS
 ack.vim/
 aws-vim/
 sudo.vim/
** syntastic/**
 tabular/
 vim-airline/
 vim-airline-themes/
 vim-better-whitespace/
 vim-fugitive/
 vim-gitgutter/
 vim-gnupg/
 vim-json/
 vim-puppet/
 vim-shellcheck/

* openSUSE
22:08 $ ls -1d */
 vim-airline/
 vim-better-whitespace/
 vim-fugitive/
 vim-gitgutter/
 vim-gnupg/
 vim-shellcheck/

🟩 After adding `syntastic` also on openSUSE it works for me with `:w` to `shellcheck` also on openSUSE. Thank you for this "hint" 😄 That's the way I like it 👍🏻

**Comment by thomasmerz** [comment]
@itspriddle , have you any idea after my update?
